name: khalti_flutter_example
description: A new Flutter project.
publish_to: none
version: 1.0.1

environment:
  sdk: '>=3.1.0-262.1.beta <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  intl: ^0.19.0
  khalti_flutter:
    path: ../../khalti_flutter/
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
